### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by PierSilvioLucchese** [Nyroxz/Hwid-Temp-Spoofer#1]
Hello there, I stumbled upon your code while searching for a spoofer source code. I must say, I find your work interesting. Would it be possible to contact you on Discord for a friendly chat and perhaps exchange some thoughts?

**Comment by Nyroxz** [comment]
> Hello there, I stumbled upon your code while searching for a spoofer source code. I must say, I find your work interesting. Would it be possible to contact you on Discord for a friendly chat and perhaps exchange some thoughts?

Thanks, Sure 
Discord: xdpodf
